class LogInModel {
  int? users_fleet_id, parent_id;
  String? one_signal_id,
      user_type,
      wallet_amount,
      online_status,
      availability,
      last_activity,
      bookings_ratings,
      first_name,
      last_name,
      phone,
      email,
      password,
      profile_pic,
      address,
      national_identification_no,
      driving_license_no,
      driving_license_front_image,
      driving_license_back_image,
      cac_certificate,
      latitude,
      longitude,
      google_access_token,
      account_type,
      social_account_type,
      badge_verified,
      notifications,
      messages,
      update_profile,
      verify_email_otp,
      verify_email_otp_created_at,
      email_verified,
      verify_phone_otp,
      verify_phone_otp_created_at,
      phone_verified,
      forgot_pwd_otp,
      forgot_pwd_otp_created_at,
      date_added,
      date_modified,
      status;

  LogInModel({
    this.users_fleet_id,
    this.parent_id,
    this.one_signal_id,
    this.user_type,
    this.wallet_amount,
    this.online_status,
    this.bookings_ratings,
    this.first_name,
    this.last_name,
    this.phone,
    this.email,
    this.password,
    this.profile_pic,
    this.address,
    this.national_identification_no,
    this.driving_license_no,
    this.driving_license_front_image,
    this.driving_license_back_image,
    this.cac_certificate,
    this.latitude,
    this.longitude,
    this.google_access_token,
    this.account_type,
    this.social_account_type,
    this.badge_verified,
    this.notifications,
    this.messages,
    this.update_profile,
    this.verify_email_otp,
    this.verify_email_otp_created_at,
    this.email_verified,
    this.verify_phone_otp,
    this.verify_phone_otp_created_at,
    this.phone_verified,
    this.forgot_pwd_otp,
    this.forgot_pwd_otp_created_at,
    this.date_added,
    this.date_modified,
    this.status,
    this.availability,
    this.last_activity,
  });

  factory LogInModel.fromJson(Map<String, dynamic> json) {
    return LogInModel(
      users_fleet_id: json["users_fleet_id"] ?? -1,
      parent_id: json["parent_id"] ?? -1,
      one_signal_id: json["one_signal_id"] ?? '',
      user_type: json["user_type"] ?? '',
      wallet_amount: json["wallet_amount"] ?? '',
      online_status: json["online_status"] ?? '',
      bookings_ratings: json["bookings_ratings"] ?? '',
      first_name: json["first_name"] ?? '',
      last_name: json["last_name"] ?? '',
      phone: json["phone"] ?? '',
      email: json["email"] ?? '',
      password: json["password"] ?? '',
      profile_pic: json["profile_pic"] ?? '',
      address: json["address"] ?? '',
      national_identification_no: json["national_identification_no"] ?? '',
      driving_license_no: json["driving_license_no"] ?? '',
      driving_license_front_image: json["driving_license_front_image"] ?? '',
      driving_license_back_image: json["driving_license_back_image"] ?? '',
      cac_certificate: json["cac_certificate"] ?? '',
      latitude: json["latitude"] ?? '',
      longitude: json["longitude"] ?? '',
      google_access_token: json["google_access_token"] ?? '',
      account_type: json["account_type"] ?? '',
      social_account_type: json["social_account_type"] ?? '',
      badge_verified: json["badge_verified"] ?? '',
      notifications: json["notifications"] ?? '',
      messages: json["messages"] ?? '',
      update_profile: json["update_profile"] ?? '',
      verify_email_otp: json["verify_email_otp"] ?? '',
      verify_email_otp_created_at: json["verify_email_otp_created_at"] ?? '',
      email_verified: json["email_verified"] ?? '',
      verify_phone_otp: json["verify_phone_otp"] ?? '',
      verify_phone_otp_created_at: json["verify_phone_otp_created_at"] ?? '',
      phone_verified: json["phone_verified"] ?? '',
      forgot_pwd_otp: json["forgot_pwd_otp"] ?? '',
      forgot_pwd_otp_created_at: json["forgot_pwd_otp_created_at"] ?? '',
      date_added: json["date_added"] ?? '',
      date_modified: json["date_modified"] ?? '',
      status: json["status"] ?? '',
      availability: json["availability"] ?? '',
      last_activity: json["last_activity"] ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      "users_fleet_id": users_fleet_id,
      "parent_id": parent_id,
      "one_signal_id": one_signal_id,
      "user_type": user_type,
      "wallet_amount": wallet_amount,
      "online_status": online_status,
      "bookings_ratings": bookings_ratings,
      "first_name": first_name,
      "last_name": last_name,
      "phone": phone,
      "email": email,
      "password": password,
      "profile_pic": profile_pic,
      "address": address,
      "national_identification_no": national_identification_no,
      "driving_license_no": driving_license_no,
      "driving_license_front_image": driving_license_front_image,
      "driving_license_back_image": driving_license_back_image,
      "cac_certificate": cac_certificate,
      "latitude": latitude,
      "longitude": longitude,
      "google_access_token": google_access_token,
      "account_type": account_type,
      "social_account_type": social_account_type,
      "badge_verified": badge_verified,
      "notifications": notifications,
      "messages": messages,
      "update_profile": update_profile,
      "verify_email_otp": verify_email_otp,
      "verify_email_otp_created_at": verify_email_otp_created_at,
      "email_verified": email_verified,
      "verify_phone_otp": verify_phone_otp,
      "verify_phone_otp_created_at": verify_phone_otp_created_at,
      "phone_verified": phone_verified,
      "forgot_pwd_otp": forgot_pwd_otp,
      "forgot_pwd_otp_created_at": forgot_pwd_otp_created_at,
      "date_added": date_added,
      "date_modified": date_modified,
      "status": status,
      "availability": availability,
      "last_activity": last_activity,
    };
  }

//
}
