class SignUpModel {
  String? users_customers_type,
      first_name,
      last_name,
      phone,
      email,
      password,
      profession,
      fleet_code,
      profile_pic,
      fleet_name,
      address,
      cac_certificate,
      license_front_image,
      license_back_image,
      email_verified,
      notifications,
      messages,
      updation_permitted,
      account_type,
      social_acc_type,
      added_at,
      updated_at,
      phone_verified,
      status;
  int? national_identity_no,
      users_customers_id,
      license_no,
      verify_email_otp,
      verify_phone_otp,
      forgot_password_otp;

  SignUpModel({
    this.status,
    this.address,
    this.account_type,
    this.added_at,
    this.cac_certificate,
    this.email,
    this.email_verified,
    this.first_name,
    this.fleet_code,
    this.fleet_name,
    this.forgot_password_otp,
    this.last_name,
    this.license_back_image,
    this.license_front_image,
    this.license_no,
    this.messages,
    this.national_identity_no,
    this.notifications,
    this.password,
    this.phone,
    this.phone_verified,
    this.profession,
    this.profile_pic,
    this.social_acc_type,
    this.updated_at,
    this.updation_permitted,
    this.users_customers_id,
    this.users_customers_type,
    this.verify_email_otp,
    this.verify_phone_otp,
  });

  factory SignUpModel.fromJson(Map<String, dynamic> json) {
    return SignUpModel(
      users_customers_type: json["users_customers_type"] ?? '',
      first_name: json["first_name"] ?? '',
      last_name: json["last_name"] ?? '',
      phone: json["phone"] ?? '',
      email: json["email"] ?? '',
      password: json["password"] ?? '',
      profession: json["profession"] ?? '',
      fleet_code: json["fleet_code"] ?? '',
      profile_pic: json["profile_pic"] ?? '',
      fleet_name: json["fleet_name"] ?? '',
      address: json["address"] ?? '',
      cac_certificate: json["cac_certificate"] ?? '',
      license_front_image: json["license_front_image"] ?? '',
      license_back_image: json["license_back_image"] ?? '',
      email_verified: json["email_verified"] ?? '',
      notifications: json["notifications"] ?? '',
      messages: json["messages"] ?? '',
      updation_permitted: json["updation_permitted"] ?? '',
      account_type: json["account_type"] ?? '',
      social_acc_type: json["social_acc_type"] ?? '',
      added_at: json["added_at"] ?? '',
      updated_at: json["updated_at"] ?? '',
      phone_verified: json["phone_verified"] ?? '',
      status: json["status"] ?? '',
      national_identity_no: json["national_identity_no"],
      users_customers_id: json["users_customers_id"],
      license_no: json["license_no"],
      verify_email_otp: json["verify_email_otp"],
      verify_phone_otp: json["verify_phone_otp"],
      forgot_password_otp: json["forgot_password_otp"],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      "users_customers_type": users_customers_type,
      "first_name": first_name,
      "last_name": last_name,
      "phone": phone,
      "email": email,
      "password": password,
      "profession": profession,
      "fleet_code": fleet_code,
      "profile_pic": profile_pic,
      "fleet_name": fleet_name,
      "address": address,
      "cac_certificate": cac_certificate,
      "license_front_image": license_front_image,
      "license_back_image": license_back_image,
      "email_verified": email_verified,
      "notifications": notifications,
      "messages": messages,
      "updation_permitted": updation_permitted,
      "account_type": account_type,
      "social_acc_type": social_acc_type,
      "added_at": added_at,
      "updated_at": updated_at,
      "phone_verified": phone_verified,
      "status": status,
      "national_identity_no": national_identity_no,
      "users_customers_id": users_customers_id,
      "license_no": license_no,
      "verify_email_otp": verify_email_otp,
      "verify_phone_otp": verify_phone_otp,
      "forgot_password_otp": forgot_password_otp,
    };
  }
//
}
